### ISSUE TITLE
Add London Underground styles

### ISSUE THREAD

**Issue by fbigummy** [ProgrammerLP/Create-Trainutilities#5]

**Comment by fbigummy** [comment]
there are a few due to the age of the network 


1972 stock

![image](https://github.com/user-attachments/assets/19139bc9-06f2-40cd-b6cd-2f3ce70c1df7) 
![image](https://github.com/user-attachments/assets/3504871d-499b-4e74-8d21-29e6cc01b0b6)

1973 Stock
![image](https://github.com/user-attachments/assets/51d77cc5-9005-44a5-b3d0-05f750f30f02)
![image](https://github.com/user-attachments/assets/e7bc3ee2-a60e-4931-b661-79ffce5db34b)


S7 Stock

![image](https://github.com/user-attachments/assets/7000c85b-2c59-48cf-8865-17aca21ca0af)
![image](https://github.com/user-attachments/assets/d8e901aa-e454-4149-95cd-d886ac88847c)


Overground (unfortunately could not find without sticker on the door)
![image](https://github.com/user-attachments/assets/05e8d415-e853-4c47-834f-61da26e75b13)


elizabeth line
![image](https://github.com/user-attachments/assets/441feb59-c0db-44d4-9bc8-e7a961bcff82)

**Comment by ProgrammerLP** [comment]
Do you want only the doors?
Do you want also the front doors?

**Comment by fbigummy** [comment]
Yeah only the doors, the other stuff is easy to make using create copycat+
If we can get the font doors as well that would be grand

**Comment by ProgrammerLP** [comment]
that would be 10 doors, as that's really a lot and some of them look very similar and I can't fit that level of detail into a Minecraft model, I would suggest you can go for 4.
You can decide which ones those are :D

**Comment by ProgrammerLP** [comment]
@fbigummy

**Comment by ProgrammerLP** [comment]
ok i will also add s7 stock front door 👍

**Comment by ProgrammerLP** [comment]
Do you happen to have the door sound of the trains in good quality?

**Comment by ProgrammerLP** [comment]
Coming in v2.2.0
