### ISSUE TITLE
New doors?

### ISSUE THREAD

**Issue by Othercakes** [ProgrammerLP/Create-Trainutilities#6]
First of all, congrats for making this amazing mod! Second, are you planning to add doors with different textures? Something like the Create Mod sliding doors designs, but with different color palettes, like gray, light gray and so on.

**Comment by ProgrammerLP** [comment]
first of all, thank you very much for the kind words!

Do you mean doors like this, which have also a texture like this?
![SmartSelect_20240814_142908_Startpage.png](https://github.com/user-attachments/assets/1582423a-bc96-4208-a66b-9d947abf8c40)

**Comment by Othercakes** [comment]
Yes! I was thinking about more designs that would work better with the create mod "vanilla-like" look, you know? But with more variations, like a sliding glass door, with andesite/zinc/iron texture around the glass frame, for example.

**Comment by Othercakes** [comment]
I made a quick demonstration of what i mean: 
![image](https://github.com/user-attachments/assets/59beb7ee-14e3-439f-a938-aad136e0dd5b)

Something around these lines, but with textures resembling andesite, zinc, iron etc, to make modern trains/metro trains.

**Comment by ProgrammerLP** [comment]
Ok, I see what you mean.
In principle it is possible, I think it is a very good idea, but there is a catch. I am really bad at creating textures, especially detailed ones like vanilla textures. However, since I really like your example, you can send me the textures for the doors that you want and I will add them. Of course, only if you want to.

**Comment by Othercakes** [comment]
Sure thing. We could maybe make a collab together. How can i contact you? Are you available on discord or something else?

**Comment by ProgrammerLP** [comment]
Yeah, simply join the create: trainutilities discord server there you can find me, and then you can send it via direct message or open a suggestion on the dc server.

Thanks for your support 🙂

**Comment by ProgrammerLP** [comment]
Coming in v2.2.0
